# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VillagerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_villager_window(object):
    def setupUi(self, villager_window):
        villager_window.setObjectName("villager_window")
        villager_window.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(villager_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(villager_window)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(villager_window)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtWidgets.QLabel(villager_window)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox = QtWidgets.QSpinBox(villager_window)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(villager_window)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(villager_window)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(villager_window)
        QtCore.QMetaObject.connectSlotsByName(villager_window)

    def retranslateUi(self, villager_window):
        _translate = QtCore.QCoreApplication.translate
        villager_window.setWindowTitle(_translate("villager_window", "Form"))
        self.label.setText(_translate("villager_window", "Dofzentrum"))
        self.label_2.setText(_translate("villager_window", "Anzahl"))
        self.pushButton.setText(_translate("villager_window", "Ausbilden"))
        self.pushButton_2.setText(_translate("villager_window", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    villager_window = QtWidgets.QWidget()
    ui = Ui_villager_window()
    ui.setupUi(villager_window)
    villager_window.show()
    sys.exit(app.exec_())
